### PR TITLE
#21 testing with cmake

### PR DESCRIPTION
**Pull request by VGeorgee**

### CODE REVIEW

**Comment by BeardOfDoom** [comment]
Since it is a single header library, in my opinion the test should be separated to one file for every feature, because from the name utils.test I don't know what is included in this test, what are the utils?

**Comment by BeardOfDoom** [comment]
Can you add some randomized tests? It is great, if in these special cases the features are working fine, but what about other cases?

**Comment by BeardOfDoom** [comment]
Also a good practice in my opinion if you separate the tests where it is an obvious binary return value. (string compare return false or true.)

**Comment by battila7** [comment]
Thanks for the great comments, @BeardOfDoom !

**Review by battila7 — CHANGES_REQUESTED** [review]
It is great to see these testing efforts! However, I'd like to draw your attention to the following:

## One File per Feature

As commented by @BeardOfDoom , these tests should be separated into multiple files, organized by features. We have string operations and counters tested in the same file. This is most certainly a code smell.

## Test Functions Should Test Only One Thing

Let's look at the `sokutei_strcmp_tests` function! This contains four assertions, for four completely different test cases. If one of these assertions fail, we only know that something is wrong with `strcmp` but we do not know what exactly.

Instead of a single test function, you should place theses cases into multiple functions, for example:

~~~~C
TEST sokutei_strcmp_should_return_zero_for_empty_inputs(void) {
  // Given
  const char *input = "";
  const int expected = 0;

  // When
  const int actual = sokutei_strcmp(input, input);

  // Then
  ASSERT_EQ(actual, expected);
  PASS();
}

TEST sokutei_strcmp_should_return_zero_for_identical_non_empty_inputs(void) {
  // Given
  const char *input = "hello";
  const int expected = 0;

  // When
  const int actual = sokutei_strcmp(input, input);

  // Then
  ASSERT_EQ(actual, expected);
  PASS();
}
~~~~

Also, test functions do not have to be short. Instead, strive for making everything explicit. It should be crystal clear

  * what property is being tested,
  * what are the test inputs,
  * what forms the test setup,
  * what is the expected output,
  * how the property is tested actually,
  * what is the actual output.

Using descriptive function names and the *Given-When-Then* or *Given-Expect* structure helps a lot to achieve this clarity!

## Separation of Tests into Suites

Once you've got multiple test functions, you can create suites from them. For example, one suite for the tests of `sokutei_strcmp`, another for `sokutei_string_equals` and so on.

Only functions testing different properties of the *same* thing should go into the same suite.

## Randomized Tests (Property-based Testing?)

@BeardOfDoom also mentioned randomized tests. This idea certainly has merit to it, however, for now, I think we're fine with handwritten tests for edge cases, corner cases, negative and happy paths.

Nevertheless, we should keep in mind that the author of greatest also has a property-based testing library: https://github.com/silentbicycle/theft We might try this one out!

**Comment by battila7** [comment]
@VGeorgee  Let me know once it's ready for re-review :)

**Comment by VGeorgee** [comment]
@battila7 I think it's ready for review.

**Pull request merged**
